name: Run Codeception test cases

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Codeception Action
      uses: joelwmale/codeception-action@1.0.0

      
  
